- hosts: localhost
  become: yes
  tasks:
    - name: Stop Nginx container if running
      docker_container:
        name: shi_nginx
        state: stopped
      ignore_errors: yes

    - name: Start Nginx container
      docker_container:
        name: shi_nginx
        state: started
